channels:
  - defaults
dependencies:
  - pip
  - pytorch
  - torchvision
  - python-utils
  - matplotlib
  - pdoc3
  - pydocstyle
  - pytest
  - pylint
  - selenium
  - pandas
  - scipy
  - autopep8
  - ijson
